<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\HkdfGuard.Abstractions\HkdfGuard.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\HkdfGuard.Core\HkdfGuard.Core.csproj" />
    <ProjectReference Include="..\..\src\HkdfGuard.DataProtectionKey\HkdfGuard.DataProtectionKey.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
  </ItemGroup>

</Project>
