<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\HkdfGuard.Abstractions\HkdfGuard.Abstractions.csproj" />
    <ProjectReference Include="..\HkdfGuard.Core\HkdfGuard.Core.csproj" />
    <ProjectReference Include="..\HkdfGuard.DataProtectionKey\HkdfGuard.DataProtectionKey.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Options" />
  </ItemGroup>

</Project>
