<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\HkdfGuard.Abstractions\HkdfGuard.Abstractions.csproj" />
    <ProjectReference Include="..\HkdfGuard.Core\HkdfGuard.Core.csproj" />
    <ProjectReference Include="..\HkdfGuard.Cache\HkdfGuard.Cache.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.SecretsManager" />
  </ItemGroup>

</Project>
